name: Deploy to Neocities

on:
  push:
    branches:
      - main  # Si attiva ogni volta che carichi su questo branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false # Metti true se vuoi che i file eliminati su GitHub spariscano anche da Neocities
        dist_dir: .    # La cartella da caricare ( '.' significa tutto il repository)
